### ISSUE TITLE
Error: Cannot find module '@babel/preset-react' from '/home/circleci/project/packages/metax'

### ISSUE THREAD

**Issue by jimmyandrade** [muy/metax#6]
```
metax: [!] (plugin babel) Error: Cannot find module '@babel/preset-react' from '/home/circleci/project/packages/metax'
metax: lib/index.js
metax: Error: Cannot find module '@babel/preset-react' from '/home/circleci/project/packages/metax'
metax:     at Function.resolveSync [as sync] (/home/circleci/project/node_modules/resolve/lib/sync.js:89:15)
metax:     at resolveStandardizedName (/home/circleci/project/node_modules/@babel/core/lib/config/files/plugins.js:101:31)
metax:     at resolvePreset (/home/circleci/project/node_modules/@babel/core/lib/config/files/plugins.js:58:10)
metax:     at loadPreset (/home/circleci/project/node_modules/@babel/core/lib/config/files/plugins.js:77:20)
metax:     at createDescriptor (/home/circleci/project/node_modules/@babel/core/lib/config/config-descriptors.js:154:9)
metax:     at items.map (/home/circleci/project/node_modules/@babel/core/lib/config/config-descriptors.js:109:50)
metax:     at Array.map (<anonymous>)
metax:     at createDescriptors (/home/circleci/project/node_modules/@babel/core/lib/config/config-descriptors.js:109:29)
metax:     at createPresetDescriptors (/home/circleci/project/node_modules/@babel/core/lib/config/config-descriptors.js:101:10)
metax:     at presets (/home/circleci/project/node_modules/@babel/core/lib/config/config-descriptors.js:47:19)
 
lerna ERR! rollup -c exited 1 in 'metax'
lerna ERR! rollup -c stderr:

lib/index.js → dist/index.cjs.js, dist/index.esm.js...

[!] (plugin babel) Error: Cannot find module '@babel/preset-react' from '/home/circleci/project/packages/metax'

lib/index.js

Error: Cannot find module '@babel/preset-react' from '/home/circleci/project/packages/metax'

    at Function.resolveSync [as sync] (/home/circleci/project/node_modules/resolve/lib/sync.js:89:15)
    at resolveStandardizedName (/home/circleci/project/node_modules/@babel/core/lib/config/files/plugins.js:101:31)
    at resolvePreset (/home/circleci/project/node_modules/@babel/core/lib/config/files/plugins.js:58:10)
    at loadPreset (/home/circleci/project/node_modules/@babel/core/lib/config/files/plugins.js:77:20)
    at createDescriptor (/home/circleci/project/node_modules/@babel/core/lib/config/config-descriptors.js:154:9)
    at items.map (/home/circleci/project/node_modules/@babel/core/lib/config/config-descriptors.js:109:50)
    at Array.map (<anonymous>)
    at createDescriptors (/home/circleci/project/node_modules/@babel/core/lib/config/config-descriptors.js:109:29)
    at createPresetDescriptors (/home/circleci/project/node_modules/@babel/core/lib/config/config-descriptors.js:101:10)
    at presets (/home/circleci/project/node_modules/@babel/core/lib/config/config-descriptors.js:47:19)

lerna ERR! rollup -c exited 1 in 'metax'
npm ERR! code ELIFECYCLE
npm ERR! errno 1
npm ERR! metax-root@1.0.0 build: `lerna exec --parallel -- rollup -c`
npm ERR! Exit status 1
npm ERR! 
npm ERR! Failed at the metax-root@1.0.0 build script.
npm ERR! This is probably not a problem with npm. There is likely additional logging output above.

npm ERR! A complete log of this run can be found in:
npm ERR!     /home/circleci/.npm/_logs/2020-06-06T13_23_38_825Z-debug.log
```

**Comment by jimmyandrade** [comment]
Closed by https://github.com/muy/metax/commit/1fd0e86b94b4e06bfc930998b7344d1846510390
